<?php
echo '<footer class="footer-area">';
echo '<div class="row">';
echo '<div class="col-lg-2"></div>';
echo '<div class="col-lg-10">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-12 col-md-3">';
echo '<div class="footer-single-widget">';
echo '<img src="/QuanLy/images/logofooter.png" alt="logofooter" style="padding-bottom: 20px;">';
echo '</div>';
echo '</div>';
echo '<div class="col-12 col-md-4 section-padding-0">';
echo '<h3>TRƯỜNG ĐẠI HỌC KHOA HỌC TỰ NHIÊN</h3>';
echo '<p><strong>ĐỊA CHỈ</strong>: 334 Nguyễn Trãi - Thanh Xuân - Hà Nội </p>';
echo '<p><strong>Điện thoại</strong>: (84) 0243-8584615 / 8581419 </p>';
echo '<p><strong>Fax</strong>: (84) 0243-8583061 </p>';
echo '<p><strong>Email</strong>: hus@vnu.edu.vn hoặc admin@hus.edu.vn </p>';
echo '</div>';
echo '<div class="col-12 col-md-3">';
echo '<h3>THÔNG TIN HỮU ÍCH</h3>';
echo '<div class="footer-single-widget">';
echo '<ul class="footer-menu d-flex justify-content-between">';
echo '<li><a>Website VNU</a></li>';
echo '<li><a>Thư điện tử VNU</a></li>';
echo '<li><a>Tài liệu biểu mẫu</a></li>';
echo '<li><a>Tài nguyên số</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-12 col-md-2 pd-0">';
echo '<h3>Mạng xã hội</h3>';
echo '<p class="social"><i class="fa fa-facebook"></i>Fanpage Trường ĐHKHTN</p>';
echo '<p class="social"><i class="fa fa-facebook"></i>Fanpage Tư vấn tuyển sinh</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';